### ISSUE TITLE
I got an error when running 03run_architechture.py

### ISSUE THREAD

**Issue by MerlotQ** [varunj/AirGestAR#1]
I used the data provided. What could be the possible problem? Thanks.
I am using Python 2.7.12 and installed tensorflow via pip on ubuntu 16.04.
`
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /media/iic/28D01AA9D01A7D6E/gesture recognition/AirGestAR-master/utils.py:222: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
Traceback (most recent call last):
  File "/media/iic/28D01AA9D01A7D6E/gesture recognition/AirGestAR-master/3run_architecture.py", line 42, in <module>
    keypoints_scoremap_tf, keypoint_coord3d_tf = net.inference(image_tf, hand_side_tf, evaluation)
  File "/media/iic/28D01AA9D01A7D6E/gesture recognition/AirGestAR-master/net.py", line 37, in inference
    hand_mask = single_obj_scoremap(hand_scoremap)
  File "/media/iic/28D01AA9D01A7D6E/gesture recognition/AirGestAR-master/utils.py", line 246, in single_obj_scoremap
    max_loc = find_max_location(scoremap_fg)
  File "/media/iic/28D01AA9D01A7D6E/gesture recognition/AirGestAR-master/utils.py", line 228, in find_max_location
    xy_loc.append(tf.concat(0, [x_loc, y_loc]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1179, in concat
    tensor_shape.scalar())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 764, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 1) and () are incompatible
`

**Comment by MerlotQ** [comment]
I see I was using the latest version of tensorflow and function concat has changed its definition.

**Comment by varunj** [comment]
Great that you could figure that by yourself!
